# Generated by Django 4.2.6 on 2023-10-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_command_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='person_command_api.command'),
        ),
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
